# Generated by Django 4.2.4 on 2023-08-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infos',
            name='name',
            field=models.CharField(default='DEP de Constntine', max_length=50, verbose_name='informations about DEP'),
        ),
    ]
