# Generated by Django 4.2.4 on 2023-08-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depapp', '0002_alter_infos_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appelsoffre',
            name='type',
            field=models.CharField(choices=[('AD', "Appel d'offre"), ('CS', 'Consultations'), ('GG', 'Grie a Grie')], default='AD', max_length=2),
        ),
        migrations.AlterField(
            model_name='infos',
            name='directeurImage',
            field=models.ImageField(blank=True, null=True, upload_to='Direction/', verbose_name='Photo du Directeur'),
        ),
        migrations.AlterField(
            model_name='infos',
            name='directeurInformations',
            field=models.TextField(blank=True, null=True, verbose_name='Informations '),
        ),
        migrations.AlterField(
            model_name='infos',
            name='name',
            field=models.CharField(default='DEP de Constntine', max_length=50, verbose_name='name'),
        ),
    ]
