# Generated by Django 4.2.4 on 2023-08-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depapp', '0003_alter_appelsoffre_type_alter_infos_directeurimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='Etat',
            field=models.CharField(choices=[('R', 'Récent'), ('E', 'En cours'), ('A', 'Achevé')], default='R', max_length=1),
        ),
    ]
