# Generated by Django 4.2.4 on 2023-08-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depapp', '0004_alter_projet_etat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='title',
        ),
        migrations.AddField(
            model_name='projet',
            name='Libellé',
            field=models.CharField(default='libellé', max_length=100, verbose_name='Libellé du projet'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='infos',
            name='name',
            field=models.CharField(default='DEP de Constntine', max_length=50, verbose_name='Dénomination'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='Etat',
            field=models.CharField(choices=[('R', 'Récent'), ('E', 'En cours'), ('A', 'Achevé')], default='R', max_length=1, verbose_name='Etat du projet'),
        ),
    ]
