# Generated by Django 4.2.4 on 2023-10-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depapp', '0005_remove_projet_title_projet_libellé_alter_infos_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appelsoffre',
            name='type',
            field=models.CharField(choices=[('AD', "Appel d'offre"), ('CS', 'Consultations'), ('GG', 'Grie a Grie')], default='AD', max_length=20),
        ),
    ]
