# Generated by Django 4.2.4 on 2023-10-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depapp', '0006_alter_appelsoffre_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='secteur',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to="Secteurs d'activité/"),
        ),
    ]
