# Generated by Django 4.2.4 on 2023-10-01 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('depapp', '0007_secteur_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Secteur',
            new_name='SecteurActivité',
        ),
    ]
