# Generated by Django 4.2.4 on 2023-10-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depapp', '0008_rename_secteur_secteuractivité'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='logo',
            field=models.ImageField(blank=True, upload_to='BET/'),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='logo',
            field=models.ImageField(blank=True, upload_to='Entreprise/'),
        ),
        migrations.AlterField(
            model_name='infos',
            name='directeurImage',
            field=models.ImageField(blank=True, upload_to='Direction/', verbose_name='Photo du Directeur'),
        ),
        migrations.AlterField(
            model_name='infos',
            name='image1',
            field=models.ImageField(blank=True, upload_to='Direction/'),
        ),
        migrations.AlterField(
            model_name='infos',
            name='image2',
            field=models.ImageField(blank=True, upload_to='Direction/'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='image',
            field=models.ImageField(blank=True, upload_to='Projets/'),
        ),
        migrations.AlterField(
            model_name='projetimages',
            name='image',
            field=models.ImageField(blank=True, upload_to='Projets/Images/'),
        ),
        migrations.AlterField(
            model_name='secteuractivité',
            name='image',
            field=models.ImageField(blank=True, upload_to="Secteurs d'activité/"),
        ),
        migrations.AlterField(
            model_name='service',
            name='photo',
            field=models.ImageField(blank=True, upload_to='Chef_Service/'),
        ),
    ]
