# Generated by Django 4.2.4 on 2023-10-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depapp', '0009_alter_bet_logo_alter_entreprise_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='secteuractivité',
            name='afficherDroite',
            field=models.BooleanField(default=False),
        ),
    ]
