# Generated by Django 4.2.4 on 2023-10-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depapp', '0010_secteuractivité_afficherdroite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appelsoffre',
            name='type',
            field=models.CharField(choices=[('AppelOffre', "Appel d'offre"), ('Consultations', 'Consultations'), ('GrieaGrie', 'Grie a Grie')], default='AppelOffre', max_length=20),
        ),
    ]
