# Generated by Django 4.2.4 on 2023-10-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depapp', '0011_alter_appelsoffre_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appelsoffre',
            name='type',
            field=models.CharField(choices=[("Appel d'offre", "Appel d'offre"), ('Consultation', 'Consultation'), ('Grie a Grie', 'Grie a Grie')], default="Appel d'offre", max_length=20),
        ),
    ]
