# Generated by Django 4.2.4 on 2023-10-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depapp', '0012_alter_appelsoffre_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='Etat',
            field=models.CharField(choices=[('Récent', 'Récent'), ('En cours', 'En cours'), ('Achevé', 'Achevé')], default='Récent', max_length=20, verbose_name='Etat du projet'),
        ),
    ]
