# Generated by Django 4.2.4 on 2023-10-03 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('depapp', '0013_alter_projet_etat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projet',
            old_name='Libellé',
            new_name='libellé',
        ),
        migrations.RenameField(
            model_name='projet',
            old_name='Etat',
            new_name='état',
        ),
    ]
