# Generated by Django 4.2.8 on 2023-12-05 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('depapp', '0014_rename_libellé_projet_libellé_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='date_début_traveaux',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projet',
            name='secteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Secteurs', to='depapp.secteuractivité', verbose_name="Secteur d'activité"),
        ),
    ]
