# Generated by Django 4.2.8 on 2023-12-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depapp', '0015_projet_date_début_traveaux_alter_projet_secteur'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffreEmploi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libellé', models.CharField(max_length=100, verbose_name='Libellé du projet')),
                ('description', models.TextField(blank=True, null=True)),
                ('nombre_poste', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('date_début', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('afficher', models.BooleanField(default=False)),
            ],
        ),
    ]
