# Generated by Django 4.2.8 on 2023-12-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depapp', '0016_offreemploi'),
    ]

    operations = [
        migrations.AddField(
            model_name='appelsoffre',
            name='afficher',
            field=models.BooleanField(default=False),
        ),
    ]
