# Generated by Django 4.2.8 on 2023-12-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depapp', '0017_appelsoffre_afficher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
