# Generated by Django 4.2.8 on 2023-12-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depapp', '0018_alter_bet_active_alter_entreprise_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='afficher',
            field=models.BooleanField(default=False),
        ),
    ]
