# Generated by Django 4.2.8 on 2023-12-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depapp', '0019_alter_projet_afficher'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='date_fin_traveaux',
            field=models.DateField(blank=True, null=True),
        ),
    ]
