# Generated by Django 4.2.8 on 2023-12-10 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('depapp', '0020_projet_date_fin_traveaux'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bet',
            old_name='active',
            new_name='afficher',
        ),
        migrations.RenameField(
            model_name='entreprise',
            old_name='active',
            new_name='afficher',
        ),
        migrations.RemoveField(
            model_name='offreemploi',
            name='libellé',
        ),
        migrations.RemoveField(
            model_name='offreemploi',
            name='nombre_poste',
        ),
    ]
